# ------------------------------------------------------------------------------
#
# Maintainer:   jeffskinnerbox@yahoo.com / www.jeffskinnerbox.me
# Version:      1.0.0
#
# DESCRIPTION
#     Gotify self-hosted Docker container that makes sending & receiving real-time
#     notifications/messages easy. By self-hosted your notifications your data
#     isn't be used by any of the comercial servers in the market. It send messages
#     via REST-API and receive messages via WebSocket.
#
# USAGE
#     For push message examples, see https://gotify.net/docs/more-pushmsg and https://github.com/gotify/cli
#         curl -X POST http://localhost:8070/message?token=ArEooNjRXNE67qj -F "title=Test Notification" -F "message=status concerning something important"
#         curl http://localhost:8070/message?token=ArEooNjRXNE67qj -s -S --data '{"message": "Hello: ![](https://gotify.net/img/logo.png) - status concerning something important", "title": "Test Notification", "priority":'10', "extras": {"client::display": {"contentType": "text/markdown"}}}' -H 'Content-Type: application/json'
#
#         Test pushover ...
#         curl --silent -F "token=a24CwQiK9KfxdLxV6wmir4o7c3rFVD" -F "user=u7pVGpnNFYQHy9aUNcyEVKGfzqezyx" -F "message=MESSAGE" -F "device=desktop" -F "title=TITLE" -F "sound=spacealarm" https://api.pushover.net/1/messages.json 
#
# TESTING
#     YAML linter to spot YAML syntax errors
#         yamllint docker-compose.yml
#     To start this docker container for validation
#         sudo docker compose up
#     To stop & remove container for compose file modification
#         sudo docker kill pushtify
#         sudo docker irm pushtify
#
# ACCESS
#     To access gotify GUI when deployed
#         http://localhost:8070, in my cause http://192.168.1.200:8070
#
# TOOLS
#     https://www.composeverter.com - convert your `docker compose` file from V1 to V2 (2.x, 3.x, common specification)
#     https://www.composerize.com - convert `docker run` command to `docker compose`
#     https://www.decomposerize.com - convert `docker compose` command to `docker run`
#
# SOURCES
#     [Gotify: My New Favorite Way To Get Notified!](https://www.youtube.com/watch?v=mIVHxFrFKqQ)
#     [Create Notifications For ANYTHING Using Gotify (Crowdsec, Cron Jobs, Scripts, Uptime, File Copy)](https://www.youtube.com/watch?v=Ft69PY7iitw)
#
# ------------------------------------------------------------------------------

---

services:
  pushtify:
    image: ghcr.io/sebw/pushtify:latest
    container_name: pushtify
    restart: unless-stopped
    environment:
      - GOTIFY_TOKEN="ChEho62Mz.xUHl3"
      - PUSHOVER_USERKEY="u7pVGpnNFYQHy9aUNcyEVKGfzqezyx"
      - GOTIFY_HOST=192.168.1.200:8070
