
#  push notification scheme for my home lab environment

version: '3.8'

services:
  apprise-api:
    image: caronc/apprise:latest
    container_name: apprise
    restart: unless-stopped
    ports:
      - '8005:8000'
    volumes:
      - /home/jeff/src/docker-containers/notification-server/config:/config
      - /var/lib/apprise/attach:/attach      # used for file attachments, you do not have to mount this if you don't intend to use it
    environment:
      - APPRISE_WORKER_COUNT=1               # all that is needed for a light-weight self-hosted solution

  mailrise:
    image: yoryan/mailrise:latest
    container_name: mailrise
    restart: unless-stopped
    ports:
      - '8025:8025'
    volumes:
      - /home/jeff/src/docker-containers/notification-server/config/mailrise.conf:/etc/mailrise.conf

