
# ------------------------------------------------------------------------------
#
# Maintainer:   jeffskinnerbox@yahoo.com / www.jeffskinnerbox.me
# Version:      1.0.0
#
# DESCRIPTION
#     Speedtest Tracker is a self-hosted internet performance tracking application
#     that runs speedtest checks against Ookla's Speedtest service.

# TESTING
#     YAML linter to spot YAML syntax errors
#         yamllint docker-compose.yml
#     To start this docker container for validation
#         sudo docker-compose up -d --file /home/jeff/src/homelab-portainer-stacks/stacks/desktop/speedtest/docker-compose.yml
#     To stop & remove container for compose file modification
#         sudo docker stop speedtest
#         sudo docker rm speedtest
#
# ACCESS
#     To access speedtest when deployed
#         http://<ip-of-your-server>:<port>, in my cased http://192.168.1.200:8083
#
# SOURCES
#     DockerHub: linuxserver/speedtest-tracker - https://hub.docker.com/r/linuxserver/speedtest-tracker
#     Speedtest Tracker - https://docs.speedtest-tracker.dev/
#     GitHub: alexjustesen/speedtest-tracker - https://github.com/alexjustesen/speedtest-tracker
#     Internet SpeedTest Tracker on Docker - https://www.youtube.com/watch?v=feArak6WCLw
#
# ------------------------------------------------------------------------------

---

services:
  speedtest-tracker:
    container_name: speedtest-tracker
    image: lscr.io/linuxserver/speedtest-tracker:latest
    restart: unless-stopped
    ports:
      - 8083:80
      - 8084:443
    environment:
      - PUID=1000
      - PGID=1000
      - APP_KEY="base64:mEDEbug0rP/f49ASZKQKJqA1ZKyN06SY65hXDgYJsP0="   # generate a key at `https://speedtest-tracker.dev`
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=speedtest_tracker
      - DB_USERNAME=speedy
      - DB_PASSWORD=password
      - SPEEDTEST_SCHEDULE="*/5 * * * *"                                # run speedtest every 5 minutes
      - PRUNE_RESULTS_OLDER_THAN=30                                     # after 30 days, remove speedtest data from database
      - APP_TIMEZONE="America/New_York"                                 # your location time zone
    volumes:
      - ~/src/homelab-portainer-stacks/stacks/desktop/speedtest/data:/config
      - ~/src/homelab-portainer-stacks/stacks/desktop/speedtest/data/keys:/config/keys
    depends_on:
      - db

  db:
    container_name: mariadb
    image: mariadb:10
    restart: always
    environment:
      - MARIADB_DATABASE=speedtest_tracker
      - MARIADB_USER=speedy
      - MARIADB_PASSWORD=password
      - MARIADB_RANDOM_ROOT_PASSWORD=true
    volumes:
      - speedtest-db:/var/lib/mysql

volumes:
  speedtest-db:                                                         # database is stored in /var/lib/docker/volumes

