
# ------------------------------------------------------------------------------
#
# Maintainer:   jeffskinnerbox@yahoo.com / www.jeffskinnerbox.me
# Version:      1.0.0
#
# DESCRIPTION
#    Portainer is a popular Docker UI that helps you visualise your containers,
#    images, volumes and networks. With Portainer, you centrally configure, manage,
#    and secure containerized environments, regardless of where they are hosted.
#
# TESTING
#     YAML linter to spot YAML syntax errors
#         yamllint docker-compose.yml
#     To start this docker container for validation
#         sudo docker-compose up -d --file /home/jeff/src/homelab-portainer-stacks/stacks/desktop/portainer/docker-compose.yml
#     To stop & remove container for compose file modification
#         sudo docker stop portainer
#         sudo docker rm portainer
#
# ACCESS
#     To access Portainer Agent when deployed
#         http://<ip-of-your-server>:<port>, in my cased http://192.168.1.200:9000
#
# SOURCES
#     Installing Portainer and Portainer Agent - An update to show you an easier way to manage Docker - https://www.youtube.com/watch?v=-LPaWq1_GF0
#     Add ALL of your Docker Hosts to ONE Portainer Dashboard Using the Portainer Edge Agent - https://www.youtube.com/watch?v=8YmQoQ7gAg8
#
# ------------------------------------------------------------------------------

---

version: '3'

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      #- 8000:8000               # optional and is only required if you plan to use the edge compute features with edge agents
      - 9000:9000               # http access to protainer web page
      - 9443:9443               # https access to protainer web page
    #networks:                   # needed for swarms
      #- agent_network
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

#networks:                       # needed for swarms
  #agent_network:
    #driver: overlay
    #attachable: true

volumes:
  portainer_data:               # on linux, this is /var/lib/docker/volumes a host filesystem managed by docker

