
# ------------------------------------------------------------------------------
#
# Maintainer:   jeffskinnerbox@yahoo.com / www.jeffskinnerbox.me
# Version:      1.0.0
#
# DESCRIPTION
#    Portainer is a popular Docker UI that helps you visualise your containers,
#    images, volumes and networks. With Portainer, you centrally configure, manage,
#    and secure containerized environments, regardless of where they are hosted.
#
#    The Portainer Agent runs on the node in your cluster of Docker sites
#    and communicates with the Portainer Server. This way, you can manage
#    all your docker containers from a single Portainer GUI.
#
# TESTING
#     YAML linter to spot YAML syntax errors
#         yamllint docker-compose.yml
#     To start this docker container for validation
#         sudo docker-compose up -d --file /home/jeff/src/homelab-portainer-stacks/stacks/synology/portainer-agent/docker-compose.yml
#     To stop & remove container for compose file modification
#         sudo docker stop portainer-agent
#         sudo docker rm portainer-agent
#
# ACCESS
#     To access Portainer Agent when deployed
#         http://<ip-of-your-server>:<port>, in my cased http://192.168.1.200:9000
#
# SOURCES
#     Installing Portainer and Portainer Agent - An update to show you an easier way to manage Docker - https://www.youtube.com/watch?v=-LPaWq1_GF0
#     Add ALL of your Docker Hosts to ONE Portainer Dashboard Using the Portainer Edge Agent - https://www.youtube.com/watch?v=8YmQoQ7gAg8
#
# ------------------------------------------------------------------------------

---

version: '3'

services:
  portainer:
    image: portainer/agent:latest
    container_name: portainer-agent
    restart: unless-stopped
    ports:
      - 9001:9001               # used to communicate with managing portainer
    #networks:                   # needed for swarms
      #- agent_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/var/lib/docker/volumes

#networks:                       # needed for swarms
#networks:
  #agent_network:
    #driver: overlay
    #attachable: true

volumes:
  portainer_data:               # data is stored in /var/lib/docker/volumes

