#
# Maintainer:   jeffskinnerbox@yahoo.com / www.jeffskinnerbox.me
# Version:      1.0.0
#
# Joplin is an open source note-taking app wher you can capture your thoughts
# and securely access them from any device.  Images, videos, PDFs and audio files are supported.
# You can create math expressions and diagrams directly from the app. Take photos
# with the mobile app and save them to a note.  Joplin is a free, open source note taking
# and to-do application, which can handle a large number of notes organised into notebooks.
# The notes are searchable, can be copied, tagged and modified either from the
# applications directly or from your own text editor. The notes are in Markdown format.
#
# to start this docker container for ubuntu desktop
#    cd ~/src/docker-containers/joplin
#
## start the joplin docker container via docker-compose
#    sudo docker-compose --file ./joplin-docker-compose.yml up -d
#


# Update the following fields in the docker compose text below:
#
# APP_BASE_URL
# POSTGRES_USER
# POSTGRES_PASSWORD
#
# APP_BASE_URL: This is the base public URL where the service will be running.
#	- If Joplin Server needs to be accessible over the internet, configure APP_BASE_URL as follows: https://example.com/joplin.
#	- If Joplin Server does not need to be accessible over the internet, set the the APP_BASE_URL to your server's hostname.
#     For Example: http://[hostname]:22300. The base URL can include the port.
# APP_PORT: The local port on which the Docker container will listen.
#	- This would typically be mapped to port to 443 (TLS) with a reverse proxy.
#	- If Joplin Server does not need to be accessible over the internet, the port can be mapped to 22300.

version: '3'

services:
    db:
        image: postgres:15
        volumes:
            - joplindb:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        restart: unless-stopped
        environment:
            - POSTGRES_PASSWORD=POSTGRES_PASSWORD
            - POSTGRES_USER=POSTGRES_USER
            - POSTGRES_DB=POSTGRES_DATABASE
    app:
        image: joplin/server:latest
        depends_on:
            - db
        ports:
            - "22300:22300"
        restart: unless-stopped
        environment:
            - APP_PORT=22300
            #- APP_BASE_URL=https://joplin.jeffskinnerbox.com
            - APP_BASE_URL=http://desktop:22300
            - DB_CLIENT=pg
            - POSTGRES_PASSWORD=POSTGRES_PASSWORD
            - POSTGRES_DATABASE=POSTGRES_DATABASE
            - POSTGRES_USER=POSTGRES_USER
            - POSTGRES_PORT=5432
            - POSTGRES_HOST=db
            - MAILER_ENABLED=1
            - MAILER_HOST=smtp.gmail.com
            - MAILER_PORT=465
            - MAILER_SECURE=1
            - MAILER_AUTH_USER=you@yourdomain.com
            - MAILER_AUTH_PASSWORD=3m@1lPa55w0rD
            - MAILER_NOREPLY_NAME=JoplinServer
            - MAILER_NOREPLY_EMAIL=you@yourdomain.com

volumes:
  joplindb:

