# Excalidraw is an open source virtual collaborative whiteboard for sketching
# hand-drawn like diagrams and text.  You can use it to self-host your own client under your own domain.
#
# To access Excalidraw visit
# http://<ip of your server>:<port>, in my cased http://192.168.1.200:8082
#
# To start this docker container
# sudo docker-compose --file ./excalidraw-docker-compose.yml up -d
#


version: "3.8"

services:
  excalidraw:
    image: excalidraw/excalidraw:latest
    container_name: excalidraw
    ports:
      - "8082:80"
    restart: unless-stopped
    stdin_open: true
    healthcheck:
      disable: true
    environment:
      - NODE_ENV=production
    volumes:
      - /home/jeff/src/docker-volumes/excalidraw/:/opt/node_app/app:delegated
      - /home/jeff/src/docker-volumes/excalidraw/package.json:/opt/node_app/package.json
      - /home/jeff/src/docker-volumes/excalidraw/yarn.lock:/opt/node_app/yarn.lock
      - notused:/opt/node_app/app/node_modules

volumes:
  notused:

