
# ------------------------------------------------------------------------------
#
# Maintainer:   jeffskinnerbox@yahoo.com / www.jeffskinnerbox.me
# Version:      1.0.0
#
# DESCRIPTION
#
# TESTING
#     YAML linter to spot YAML syntax errors
#         yamllint docker-compose.yml
#     To start this docker container for validation
#         sudo docker-compose up -d --file /home/jeff/src/homelab-portainer-stacks/stacks/desktop/watchtower/docker-compose.yml
#     To stop & remove container for compose file modification
#         sudo docker stop watchtower
#         sudo docker rm watchtower
#
# ACCESS
#     There is no access Watchtower when deployed
#
# SOURCES
#
# ------------------------------------------------------------------------------

---

version: '3'

services:
  watchtower:
    image: containrrr/watchtower:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: "5"   # number of files or file count
        max-size: "10m" # file size

